Fix 201 -> 204 http status.
In eed158e5 I accidentally converted an expected 201 to and expected
204.  I'd typically just squash this commit into eed158e5, but I'm not
sure how Gravitational feels about rewriting history that is under
review in a PR. So... for now this remains as its own commit.

The test was broken without this, failing with:
    AssertionError: POST /containers/<id>/start returned http status 204 instead of expected 201.